"""OpenWolf integration helpers.

OpenWolf is not a command wrapper like execwrap or RTK. It is a project memory
system backed by ``.wolf/`` files plus runtime hooks/plugins. This module wires
that memory into the runtimes langywrap can launch.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from langywrap.helpers.discovery import find_tool


def _hook_command(script: str, *, langywrap_only: bool) -> str:
    command = f'node "$CLAUDE_PROJECT_DIR/.wolf/hooks/{script}"'
    if not langywrap_only:
        return command
    return f'sh -c \'[ "$LANGYWRAP_OPENWOLF" = "1" ] || exit 0; {command}\''


def claude_hook_settings(*, langywrap_only: bool = False) -> dict[str, Any]:
    """Return Claude hook settings, optionally gated to langywrap-launched runs."""
    return {
    "SessionStart": [
        {
            "matcher": "",
            "hooks": [
                {
                    "type": "command",
                    "command": _hook_command("session-start.js", langywrap_only=langywrap_only),
                    "timeout": 5,
                }
            ],
        }
    ],
    "PreToolUse": [
        {
            "matcher": "Read",
            "hooks": [
                {
                    "type": "command",
                    "command": _hook_command("pre-read.js", langywrap_only=langywrap_only),
                    "timeout": 5,
                }
            ],
        },
        {
            "matcher": "Write|Edit|MultiEdit",
            "hooks": [
                {
                    "type": "command",
                    "command": _hook_command("pre-write.js", langywrap_only=langywrap_only),
                    "timeout": 5,
                }
            ],
        },
    ],
    "PostToolUse": [
        {
            "matcher": "Read",
            "hooks": [
                {
                    "type": "command",
                    "command": _hook_command("post-read.js", langywrap_only=langywrap_only),
                    "timeout": 5,
                }
            ],
        },
        {
            "matcher": "Write|Edit|MultiEdit",
            "hooks": [
                {
                    "type": "command",
                    "command": _hook_command("post-write.js", langywrap_only=langywrap_only),
                    "timeout": 10,
                }
            ],
        },
    ],
    "Stop": [
        {
            "matcher": "",
            "hooks": [
                {
                    "type": "command",
                    "command": _hook_command("stop.js", langywrap_only=langywrap_only),
                    "timeout": 10,
                }
            ],
        }
    ],
    }


OPENCODE_PLUGIN = r'''// Generated by langywrap: OpenWolf adapter for OpenCode.
// Bridges OpenCode plugin events to OpenWolf's Claude-style hook scripts.
// If LANGYWRAP_OPENWOLF_ONLY=1, it activates only when LANGYWRAP_OPENWOLF=1.
import { existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { spawnSync as run } from "node:child_process";

function projectRoot(ctx) {
  return resolve(ctx?.worktree || ctx?.directory || process.cwd());
}

function hookPath(root, name) {
  return join(root, ".wolf", "hooks", `${name}.js`);
}

function callHook(root, name, payload) {
  if (process.env.LANGYWRAP_OPENWOLF_ONLY === "1" && process.env.LANGYWRAP_OPENWOLF !== "1") return;
  const script = hookPath(root, name);
  if (!existsSync(script)) return;
  run("node", [script], {
    cwd: root,
    input: JSON.stringify(payload),
    encoding: "utf8",
    env: { ...process.env, CLAUDE_PROJECT_DIR: root, OPENWOLF_PROJECT_ROOT: root },
    timeout: 10_000,
    stdio: ["pipe", "ignore", "pipe"],
  });
}

function argsOf(output) {
  return output?.args || output?.input || output || {};
}

function filePathFrom(args) {
  return args.filePath || args.file_path || args.path || args.filename || "";
}

function contentFrom(args) {
  return args.content || args.text || args.newString || args.value || "";
}

function toolKind(input) {
  return String(input?.tool || input?.name || "").toLowerCase();
}

export const OpenWolfPlugin = async (ctx) => {
  const root = projectRoot(ctx);
  return {
    event: async ({ event }) => {
      if (event?.type === "session.created") callHook(root, "session-start", {});
      if (event?.type === "session.idle") callHook(root, "stop", {});
    },
    "tool.execute.before": async (input, output) => {
      const tool = toolKind(input);
      const args = argsOf(output);
      const filePath = filePathFrom(args);
      if (!filePath) return;
      const payload = { tool_input: { file_path: filePath, path: filePath, ...args } };
      if (tool === "read") callHook(root, "pre-read", payload);
      if (["write", "edit", "multiedit"].includes(tool)) callHook(root, "pre-write", payload);
    },
    "tool.execute.after": async (input, output) => {
      const tool = toolKind(input);
      const args = argsOf(output);
      const filePath = filePathFrom(args);
      if (!filePath) return;
      const content = contentFrom(args);
      const payload = {
        tool_input: { file_path: filePath, path: filePath, ...args },
        tool_output: { content },
      };
      if (tool === "read") callHook(root, "post-read", payload);
      if (["write", "edit", "multiedit"].includes(tool)) callHook(root, "post-write", payload);
    },
    "experimental.session.compacting": async (_input, output) => {
      output.context ||= [];
      output.context.push(
        "OpenWolf project memory is available under .wolf/. Preserve decisions, " +
        "repeated-read warnings, and bug learnings from .wolf/cerebrum.md, " +
        ".wolf/anatomy.md, and .wolf/buglog.json."
      );
    },
  };
};
'''


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _hook_is_openwolf(entry: dict[str, Any]) -> bool:
    hooks = entry.get("hooks")
    if not isinstance(hooks, list):
        return False
    for hook in hooks:
        if isinstance(hook, dict) and ".wolf/hooks/" in str(hook.get("command", "")):
            return True
    return False


def wire_claude(project_dir: Path, *, langywrap_only: bool = False) -> Path:
    """Merge OpenWolf's Claude hooks into ``.claude/settings.json``."""
    settings = project_dir / ".claude" / "settings.json"
    data = _read_json(settings)
    hooks = data.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        hooks = {}
        data["hooks"] = hooks

    for event, entries in claude_hook_settings(langywrap_only=langywrap_only).items():
        existing = hooks.get(event, [])
        if not isinstance(existing, list):
            existing = []
        kept = [
            entry
            for entry in existing
            if not (isinstance(entry, dict) and _hook_is_openwolf(entry))
        ]
        hooks[event] = [*kept, *entries]

    _write_json(settings, data)
    return settings


def wire_opencode(project_dir: Path, *, langywrap_only: bool = False) -> Path:
    """Install an OpenCode plugin that forwards events into OpenWolf hooks."""
    plugin = project_dir / ".opencode" / "plugins" / "openwolf.js"
    plugin.parent.mkdir(parents=True, exist_ok=True)
    content = OPENCODE_PLUGIN
    if langywrap_only:
        content = content.replace(
            "// Bridges OpenCode plugin events to OpenWolf's Claude-style hook scripts.",
            "// Bridges OpenCode plugin events to OpenWolf's Claude-style hook scripts.\n"
            "process.env.LANGYWRAP_OPENWOLF_ONLY ||= \"1\";",
        )
    plugin.write_text(content + "\n", encoding="utf-8")
    return plugin


def init_openwolf(project_dir: Path) -> bool:
    """Run ``openwolf init`` if the binary is available."""
    binary = find_tool("openwolf", project_dir)
    if binary is None:
        return False
    proc = subprocess.run(
        [binary, "init"],
        cwd=project_dir,
        text=True,
        capture_output=True,
        timeout=120,
        check=False,
    )
    return proc.returncode == 0


def openwolf_status(project_dir: Path) -> dict[str, Any]:
    """Return installation/wiring status for OpenWolf in a project."""
    wolf_dir = project_dir / ".wolf"
    claude_settings = project_dir / ".claude" / "settings.json"
    opencode_plugin = project_dir / ".opencode" / "plugins" / "openwolf.js"
    claude_data = _read_json(claude_settings)
    claude_blob = json.dumps(claude_data)
    opencode_blob = opencode_plugin.read_text(encoding="utf-8") if opencode_plugin.exists() else ""
    hooks_dir = wolf_dir / "hooks"
    required_hooks = [
        "session-start.js",
        "pre-read.js",
        "pre-write.js",
        "post-read.js",
        "post-write.js",
        "stop.js",
    ]
    missing_hooks = [name for name in required_hooks if not (hooks_dir / name).exists()]
    issues: list[str] = []
    hints: list[str] = []
    binary = find_tool("openwolf", project_dir)
    if binary is None:
        issues.append("openwolf binary not discovered")
        hints.append("Install OpenWolf with: cd ../langywrap && ./just install-openwolf")
    if not wolf_dir.exists():
        issues.append(".wolf directory is absent; run `langywrap integration openwolf wire --init`")
        hints.append(
            "Initialize and wire for langywrap-only runs with: "
            "langywrap integration openwolf wire . --init --langywrap-only"
        )
    if wolf_dir.exists() and missing_hooks:
        issues.append(".wolf/hooks is incomplete; rerun OpenWolf init")
        hints.append("Refresh OpenWolf project files with: openwolf init")
    if wolf_dir.exists() and ".wolf/hooks/" not in claude_blob:
        issues.append("Claude OpenWolf hooks are not registered")
        hints.append(
            "Wire Claude hooks with: "
            "langywrap integration openwolf wire . --no-opencode --langywrap-only"
        )
    if wolf_dir.exists() and not opencode_plugin.exists():
        issues.append("OpenCode OpenWolf plugin is not installed")
        hints.append(
            "Wire OpenCode plugin with: "
            "langywrap integration openwolf wire . --no-claude --langywrap-only"
        )

    return {
        "binary": binary,
        "wolf_dir": str(wolf_dir) if wolf_dir.exists() else None,
        "hooks_missing": missing_hooks,
        "claude_hooks": ".wolf/hooks/" in claude_blob,
        "claude_langywrap_only": "LANGYWRAP_OPENWOLF" in claude_blob,
        "opencode_plugin": str(opencode_plugin) if opencode_plugin.exists() else None,
        "opencode_langywrap_only": "LANGYWRAP_OPENWOLF_ONLY" in opencode_blob,
        "issues": issues,
        "hints": list(dict.fromkeys(hints)),
    }


def wire_openwolf(
    project_dir: Path,
    *,
    init: bool = False,
    claude: bool = True,
    opencode: bool = True,
    langywrap_only: bool = False,
) -> dict[str, Any]:
    """Initialize and wire OpenWolf into supported runtimes."""
    initialized = False
    if init and not (project_dir / ".wolf").exists():
        initialized = init_openwolf(project_dir)
    written: dict[str, str] = {}
    if claude:
        written["claude_settings"] = str(
            wire_claude(project_dir, langywrap_only=langywrap_only)
        )
    if opencode:
        written["opencode_plugin"] = str(
            wire_opencode(project_dir, langywrap_only=langywrap_only)
        )
    status = openwolf_status(project_dir)
    return {"initialized": initialized, "written": written, "status": status}
